### ISSUE TITLE
Where can the AppImage be downloaded?

### ISSUE THREAD

**Issue by probonopd** [bgallois/Fishy-Tracking#1]
Where can the AppImage be downloaded? I would like to include it on https://appimage.github.io/apps/.

**Comment by bgallois** [comment]
The AppImage can be downloaded at http://fishytracking.benjamin-gallois.fr/download.html.

**Comment by probonopd** [comment]
`AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (required by /run/firejail/appimage/.appimage-7444/AppRun)`. Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems and please compile on the oldest still-supported distribution, e.g., Ubuntu trusty.

**Comment by bgallois** [comment]
The new AppImage available at http://fishytracking.benjamin-gallois.fr/download/FishyTracking.AppImage is now compiled on Ubuntu Trusty. The problem should be corrected now.
